### ISSUE TITLE
Unable to deserialize unsigned integers

### ISSUE THREAD

**Issue by thrykol** [mehcode/config-rs#357] opened 2022-07-18 15:25 UTC
When implementing `config::ValueKind` for a custom type, the error `invalid type: unsigned integer 64 bit '128', expected an signed 64 bit or less integer for key 'inner.unsigned'` is thrown if the custom type contains a unsigned integer.  The following is a minimum example:

```
#[derive(Deserialize, Eq, PartialEq, Debug)]
struct Container<T> {
    inner: T,
}

#[derive(Deserialize, Eq, PartialEq, Debug)]
struct Unsigned {
    unsigned: u16,
}

impl Default for Unsigned {
    fn default() -> Self {
        Self { unsigned: 128 }
    }
}

impl From<Unsigned> for config::ValueKind {
    fn from(unsigned: Unsigned) -> Self {
        let mut properties = HashMap::default();
        properties.insert(
            "unsigned".to_string(),
            config::Value::from(unsigned.unsigned),
        );

        Self::Table(properties)
    }
}

assert_eq!(
    Container {
        inner: Unsigned::default()
    },
    config::Config::builder()
        .set_default("inner", Unsigned::default())
        .unwrap()
        .build()
        .unwrap()
        .try_deserialize::<Container<Unsigned>>()
        .unwrap()
);
```

**Comment by matthiasbeyer** [comment] 2022-07-23 11:40
Hi! Can you tell me where exactly that error gets thrown?

**Comment by thrykol** [comment] 2022-07-25 16:38
> Hi! Can you tell me where exactly that error gets thrown?

Unfortunately, no, I was unable to trace the origin down.

**Comment by matthiasbeyer** [comment] 2022-07-25 16:39
I mean in the above code.

**Comment by thrykol** [comment] 2022-07-25 17:02
> I mean in the above code.

Sorry... totally misunderstood you.  There error is returned from `.try_deserialize::<Container<Unsigned>>()`

**Comment by matthiasbeyer** [comment] 2022-07-26 10:43
I just added a testcase derived from your code in #359. Lets see whether I can reproduce your issue... but so far it looks like I can't!

**Comment by matthiasbeyer** [comment] 2022-07-26 10:48
Yep, I [cannot reproduce](So the test we came for [succeeds](https://github.com/mehcode/config-rs/runs/7518454547?check_suite_focus=true#step:4:582)) your issue... Maybe I've missed something, feel free to have a look at #359 and review whether it is equal to your code.

**Comment by thrykol** [comment] 2022-07-26 14:50
Only difference I can see is the switch from `HashMap` to `IndexMap`.  Tried making that change locally but it appears that `0.13.1` doesn't yet support creating a `Table` from a `HashMap`. Don't think it matters, but my Rust version is `rustc 1.62.1 (e092d0b6b 2022-07-16)`

**Comment by matthiasbeyer** [comment] 2022-07-26 16:18
> Only difference I can see is the switch from HashMap to IndexMap

That is because a `Table` is constructed using an `IndexMap` in the tests instead of a `HashMap` if the `preserve_order` feature is enabled.

**Comment by thrykol** [comment] 2022-08-01 20:55
Wondering if there might be a difference in the logic when `preserve_order` is enabled.  Have you possibly been able to duplicate with `preserve_order = false`?

**Comment by matthiasbeyer** [comment] 2022-08-02 06:45
[Yes](https://github.com/mehcode/config-rs/pull/360).

**Comment by thrykol** [comment] 2022-08-02 13:38
After cloning the repository and patching the source into my project with

```rust
[patch.crates-io]
config = { path = "../config.rs" }
```
everything works as expected. So there must be some change from `0.13.1` to `HEAD` which fixes what I'm seeing. Any chances of getting a new release out today?

**Comment by matthiasbeyer** [comment] 2022-08-02 14:05
Can you please do some more testing?

Does 7db2e8b this exact patch maybe fix your issue? If it does, I can release this as `0.13.2`.

**Comment by thrykol** [comment] 2022-08-02 14:19
[2d74d06](https://github.com/mehcode/config-rs/commit/2d74d06740f294d402997a208822b68ccea174e2) is the first commit which works for me.

**Comment by matthiasbeyer** [comment] 2022-08-02 14:29
Okay, can you test [the release-0.13.x branch on my personal repository](https://github.com/matthiasbeyer/config-rs/tree/release-0.13.x)? If that's it, I will use that to make the `0.13.2` release.

**Comment by thrykol** [comment] 2022-08-02 14:32
That branch works.

**Comment by matthiasbeyer** [comment] 2022-08-02 14:33
Awesome. `0.13.2` incoming shortly.

**Comment by matthiasbeyer** [comment] 2022-08-02 14:49
0.13.2 was just released. I'm closing this issue for now, feel free to open a new one if need be.

**Closed by matthiasbeyer** 2022-08-02 14:49 UTC
