### ISSUE TITLE
Unchecked integer range

### ISSUE THREAD

**Issue by BratSinot** [mehcode/config-rs#224] opened 2021-08-23 11:40 UTC
Greetings!

`config` lib is casting all integers like explicit type conversion through `as`. Such behaviour by design, or this is an error?

```rust
use config::Config;

fn main() {
    let mut conf = Config::new();

    conf.merge(config::File::from_str(
        r#"
        [server]
        port = 66000
        "#,
        config::FileFormat::Toml,
    ))
    .unwrap();

    let port: u16 = conf.get("server.port").unwrap();

    println!("{}", port); // output is 464
}
```

**Comment by BratSinot** [comment] 2021-08-23 11:41
Maybe duplicate of this #93.

**Comment by matthiasbeyer** [comment] 2021-08-23 12:38
Yes, this is actually a limitation.

The problem is here that the format (toml in this case, but others apply here as well) does not define the datatype (besides "Number"). By specifying `let port: u16` in your code, the value is inferred to be `u16` and the library just assumes that the number is actually a 16 bit unsigned integer.

We cannot do much here, on the library side of things, actually (or I'm wrong and someone comes up with something clever...).

We need you to know about your data, so you have to make sure that you ask for a `u32` here and all will be fine I guess.

**Comment by BratSinot** [comment] 2021-08-23 12:47
> Yes, this is actually a limitation.
> 
> The problem is here that the format (toml in this case, but others apply here as well) does not define the datatype (besides "Number"). By specifying `let port: u16` in your code, the value is inferred to be `u16` and the library just assumes that the number is actually a 16 bit unsigned integer.
> 
> We cannot do much here, on the library side of things, actually (or I'm wrong and someone comes up with something clever...).
> 
> We need you to know about your data, so you have to make sure that you ask for a `u32` here and all will be fine I guess.

Thanks for answer!
Now I'm using this workaround:
```rust
    let port: u16 = conf
        .get_int("server.port")
        .unwrap()
        .try_into() // here
        .unwrap();
```
or this:
```rust
    let port = conf
        .get_string("server.port")
        .unwrap()
        .parse::<u16>()
        .unwrap();
```

**Comment by matthiasbeyer** [comment] 2021-08-23 12:49
Okay, I'm closing this therefore, feel free to ping me if you have more questions on the matter! :smile:

**Closed by matthiasbeyer** 2021-08-23 12:49 UTC
