### ISSUE TITLE
How do I encode an array with environment variables.

### ISSUE THREAD

**Issue by whmountains** [mehcode/config-rs#102] opened 2019-03-07 19:45 UTC
Currently I can set nested struct fields from environment variables using `config::Environment::new().separator("__")`.  Is there any equivalent for environment variables?

**Comment by rydrman** [comment] 2020-09-25 16:48
looks like a duplicate of #117

**Closed** 2020-10-08 20:52 UTC

**Comment by joeky888** [comment] 2023-09-08 16:44
tl;dr:

```rust
Environment::with_prefix("APP")
                    .separator("_")
                    .list_separator(",")
                    .try_parsing(true)
```

Test it!

```fish
APP_YOUR_VAR=1,2,3 cargo run
```
